language: go
sudo: false 

notifications: 
  email:
    recipients:
      - focinfi@gmail.com
  on_success: change
  on_failure: always

go: stable

before_install:
  - go get -t -v ./...
  - sudo apt-get update
  - sudo apt-get -y install xclip notify-send

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)